### 认识 NumPy 数组对象

NumPy 数组对象，即 ndarray 对象

In [32]:
import numpy as np   # 导入 NumPy 库
data1 = np.arange(12).reshape(3, 4)  # 创建一个3行4列的数组
data1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
type(data1)

numpy.ndarray

In [34]:
data1.ndim  # 统计数组维度的个数，输出结果是2，表示二维数组

2

In [35]:
data1.size # 统计数组元素的个数，输出结果12，表示总共有12个元素

12

In [36]:
data1.shape # 数组的维度，输出结果是(3, 4)，表示3行4列

(3, 4)

In [37]:
data1.dtype # 数组元素的类型，输出结果是dtype('int64')，表示元素的类型都 int(64)

dtype('int32')

### 创建 NumPy 数组

#### 1、array() 函数：最简单方式

In [38]:
data2 = np.array([1, 2, 3])  # 创建一个一维数组
data2

array([1, 2, 3])

In [39]:
data2.ndim

1

In [40]:
data3 = np.array([[1, 2, 3], [4, 5, 6]])  # 创建一个二维数组
data3

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
data3.ndim

2

#### 2、ones()函数：创建元素值都为1

In [42]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### 3、zeros()函数：创建元素值都为0

In [43]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### 4、empty()函数：创建一个新的数组，里面的元素都是随机的，并且数据类型默认是float64

In [44]:
np.empty((2, 2))

array([[1., 2.],
       [3., 4.]])

#### 5、arange()函数：创建一个等差数组，功能等同于 range，只不过 arange 返回的是一个数组，而不是列表。

In [45]:
np.arange(1, 20, 5)

array([ 1,  6, 11, 16])

### ndarray 对象的数据类型

In [46]:
data4 = np.array([[1, 2], [3, 4]])
data4

array([[1, 2],
       [3, 4]])

In [47]:
data4.dtype

dtype('int32')

#### 查看数据类型

In [48]:
data4.dtype.name

'int32'

#### 数据类型的转换

In [49]:
data5 = data4.astype(np.float64)  # 数据类型转换为 float64
data5

array([[1., 2.],
       [3., 4.]])

In [50]:
data5.dtype.name

'float64'

### 数组运算

#### 矢量化运算

In [51]:
data1 = np.array([[1, 2, 3], [4, 5, 6]])
data2 = np.array([[4, 5, 6], [1, 2, 3]])
data1 + data2

array([[5, 7, 9],
       [5, 7, 9]])

In [52]:
data1 - data2

array([[-3, -3, -3],
       [ 3,  3,  3]])

In [53]:
data1 * data2

array([[ 4, 10, 18],
       [ 4, 10, 18]])

In [54]:
data1 / data2

array([[0.25, 0.4 , 0.5 ],
       [4.  , 2.5 , 2.  ]])

#### 数组广播

In [55]:
data3 = np.array([[0], [1], [2], [3]])
data3

array([[0],
       [1],
       [2],
       [3]])

In [56]:
data3.shape

(4, 1)

In [57]:
data4 = np.array([1, 2, 3])
data4

array([1, 2, 3])

In [58]:
data4.shape

(3,)

In [59]:
data = data3 + data4

In [60]:
data

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [61]:
data.shape

(4, 3)

#### 数组和标量运算

In [62]:
data1 = np.array([[1, 2, 3], [4, 5, 6]])
data1

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
data2 = 10
data1 + data2

array([[11, 12, 13],
       [14, 15, 16]])

In [64]:
data1 * data2

array([[10, 20, 30],
       [40, 50, 60]])

In [65]:
data1 - data2

array([[-9, -8, -7],
       [-6, -5, -4]])

In [66]:
data1 / data2 

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6]])

### ndarray 的索引和切片

整数索引和切片的基本使用

In [67]:
arr1 = np.arange(8)  # 创建一个一维数据
arr1

array([0, 1, 2, 3, 4, 5, 6, 7])

In [68]:
arr1[5]  # 获取索引为5的元素

5

In [69]:
arr1[3:5] # 获取索引为3~5的元素，但不包括5

array([3, 4])

In [70]:
arr1[1:6:2] # 获取索引为1~6的元素，步长为2

array([1, 3, 5])

In [71]:
arr2 = np.array([[1, 2, 3], [4, 5,6], [7, 8, 9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
arr2.shape

(3, 3)

In [73]:
arr2[1] # 获取索引为1的元素

array([4, 5, 6])

In [74]:
arr2[0, 1] # 获取位于第0行第1列的元素

2

In [75]:
arr2[2]

array([7, 8, 9])

In [45]:
arr2[:2]

array([[1, 2, 3],
       [4, 5, 6]])

#### 数组索引的基本使用

In [76]:
# 创建一个4行4列的二维数组
arr3 = np.arange(16).reshape(4, 4) 
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [51]:
# 获取索引为[0, 2]的元素
arr3[[0, 2]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [77]:
# 获取索引为(1, 1) 和 (3, 2)的元素
arr3[[1, 3], [1, 2]]
# 如果使用两个数组索引操作数组时，即两个列表或数组，则会将第一个看作行索引，第2个看作列索引。

array([ 5, 14])

#### 布尔型索引的基本使用

In [78]:
# 存储学生姓名的数组
student_name = np.array(['zhangsan', 'lisi', 'wangwu', 'zhaoliu'])
student_name

array(['zhangsan', 'lisi', 'wangwu', 'zhaoliu'], dtype='<U8')

In [58]:
# 存储学生成绩的数组
student_score = np.array([[67, 78, 100], [30, 30, 100], [60, 45, 90], [100, 100, 100]])
student_score

array([[ 67,  78, 100],
       [ 30,  30, 100],
       [ 60,  45,  90],
       [100, 100, 100]])

In [59]:
# 对student_name和字符串'wangwu'通过==运算符产生一个布尔类型数组
student_name == 'wangwu'

array([False, False,  True, False])

In [60]:
# 获取数据为True值对应的行，获取wangwu学生的成绩
student_score[student_name == 'wangwu']

array([[60, 45, 90]])

In [63]:
student_name != 'wangwu'

array([ True,  True, False,  True])

In [64]:
# 获取数据为True值对应的行，获取除了wangwu以外的学生的成绩
student_score[student_name != 'wangwu']

array([[ 67,  78, 100],
       [ 30,  30, 100],
       [100, 100, 100]])

In [66]:
# 布尔型数组跟切片混合使用
student_score[student_name == 'wangwu', :2]

array([[60, 45]])