#### 1.创建一个数组，数组的shape为（5，），元素都是0

In [24]:
import numpy as np

In [32]:
arr = np.zeros((5,), dtype=np.int8)
arr

array([0, 0, 0, 0, 0], dtype=int8)

In [33]:
print(arr.shape)

(5,)


#### 2、创建一个表示国际象棋棋盘的 8 x 8 数组，其中，棋盘白格用 0 填充，棋盘黑格用 1 表示。

In [34]:
matr1=np.ones((8,8), dtype=np.int8)
for i in range(8):
    for j in range(8):
        if(i+j)%2==0:
            matr1[i,j]=0
matr1

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int8)

In [22]:
for i in range(0,8):
    for j in range(0,8):
        if matr1[i,j]==0:
            print("□",end=' ')
        else:
            print("■", end=' ')
    print('\n')

□ ■ □ ■ □ ■ □ ■ 

■ □ ■ □ ■ □ ■ □ 

□ ■ □ ■ □ ■ □ ■ 

■ □ ■ □ ■ □ ■ □ 

□ ■ □ ■ □ ■ □ ■ 

■ □ ■ □ ■ □ ■ □ 

□ ■ □ ■ □ ■ □ ■ 

■ □ ■ □ ■ □ ■ □ 



In [35]:
# 实现思路：
# 1、创建一个8 x 8 的矩阵
chesses = np.zeros((8, 8), dtype=np.int8)

In [36]:
chesses

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [37]:
# 2、行号+列号之和是奇数的设置为1
for i in range(8):
    for j in range(8):
        if (i+j)%2 != 0:
            chesses[i, j] = 1

In [38]:
chesses

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int8)