#### Numpy 通用函数

In [13]:
import numpy as np
arr = np.array([4, 9, 16])
arr

array([ 4,  9, 16])

In [14]:
# 计算数组元素的平方
np.square(arr)

array([ 16,  81, 256], dtype=int32)

In [15]:
# 计算数组元素的平方根
np.sqrt(arr)

array([2., 3., 4.])

In [16]:
x = np.array([12, 3, 65, 1])
y = np.array([11, 10, 4, 8])

In [17]:
# 计算两个数组的和
np.add(x, y)

array([23, 13, 69,  9])

In [18]:
# 计算两个数组的乘积
np.multiply(x, y)

array([132,  30, 260,   8])

In [20]:
# 两个数组中最大值的比较
np.maximum(x, y)

array([12, 10, 65,  8])

In [21]:
# 元素比较，大是True小是False
np.greater(x, y)

array([ True, False,  True, False])

### 利用Numpy数组进行数据处理

#### 将条件逻辑转为数组运算

In [28]:
x = np.array([1, 5, 7])
y = np.array([2, 6, 8])
z = np.array([True, False, True])

In [29]:
result = np.where(z, x, y)
result

array([1, 6, 7])

In [30]:
result = np.where(z, y, x)
result

array([2, 5, 8])

#### 数组统计计算

In [31]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
# 求和
arr.sum()

45

In [33]:
# 求平均值
arr.mean()

4.5

In [34]:
# 求最大值
arr.max()

9

In [35]:
# 求最小值
arr.min()

0

In [37]:
# 求最小值的索引
arr.argmin()

0

In [38]:
# 求最大值的索引
arr.argmax()

9

In [39]:
# 求元素的累计和
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [40]:
# 求元素的累计乘积
arr.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

#### 数组的排序

In [43]:
arr = np.array([[6, 2, 7], [3, 6, 2], [4, 3, 2]])
arr

array([[6, 2, 7],
       [3, 6, 2],
       [4, 3, 2]])

In [44]:
arr.sort() # sort函数会修改数组本身

In [45]:
arr

array([[2, 6, 7],
       [2, 3, 6],
       [2, 3, 4]])

In [46]:
arr = np.array([[6, 2, 7], [3, 6, 2], [4, 3, 2]])
arr

array([[6, 2, 7],
       [3, 6, 2],
       [4, 3, 2]])

In [47]:
# 按照编号为0的轴对元素进行排序
arr.sort(0)
arr

array([[3, 2, 2],
       [4, 3, 2],
       [6, 6, 7]])

#### 检索数组的元素

In [48]:
arr = np.array([[1, -3, -6], [2, 3, -9], [-4, 4, 5]])
arr

array([[ 1, -3, -6],
       [ 2,  3, -9],
       [-4,  4,  5]])

In [50]:
# 检索arr的所有元素是否有一个大于0
np.any(arr > 0)

True

In [51]:
# 检索arr的所有元素是否都大于0
np.all(arr > 0)

False

#### 唯一化

In [52]:
arr = np.array([1, 34, 88, 1, 5, 9, 11, 34, 66, 9])
arr

array([ 1, 34, 88,  1,  5,  9, 11, 34, 66,  9])

In [53]:
np.unique(arr)

array([ 1,  5,  9, 11, 34, 66, 88])

#### 其他

In [55]:
# 计算两个数组的并集
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.union1d(x, y)

array([1, 2, 3, 4, 5, 6])

### 线性代数模块

#### 矩阵点积：数组元素相乘后相加。
Numpy dot函数是用来计算两个数组之间的点积。

In [63]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[1, 2], [3, 4], [5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
y

array([[1, 2],
       [3, 4],
       [5, 6]])

In [65]:
x.dot(y)

array([[22, 28],
       [49, 64]])

In [66]:
np.dot(x, y)

array([[22, 28],
       [49, 64]])

In [67]:
y.dot(x)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [69]:
np.dot(y, x)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

#### 随机数模块
seed——生成随机数种子

rand——生成均匀分布的样本值

normal——生成正态分布的样本值

uniform——生成[0,1]范围内均匀分布的样本值

In [77]:
# 随机生成一个二维数组
np.random.rand(3, 3)

array([[0.22199317, 0.87073231, 0.20671916],
       [0.91861091, 0.48841119, 0.61174386],
       [0.76590786, 0.51841799, 0.2968005 ]])

In [81]:
# 随机生成一个三维数组
np.random.rand(2, 3, 3)

array([[[0.22199317, 0.87073231, 0.20671916],
        [0.91861091, 0.48841119, 0.61174386],
        [0.76590786, 0.51841799, 0.2968005 ]],

       [[0.18772123, 0.08074127, 0.7384403 ],
        [0.44130922, 0.15830987, 0.87993703],
        [0.27408646, 0.41423502, 0.29607993]]])

In [83]:
# 生成随机数的种子
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [84]:
np.random.seed(1)
np.random.rand(5)

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
       1.46755891e-01])

In [85]:
np.random.seed()
np.random.rand(5)

array([0.17930677, 0.44105346, 0.37962442, 0.36047248, 0.54523824])