### 综合案例——酒鬼漫步

描述：空旷的平地上有一个酒鬼，他最初停留在原点的位置，这个酒鬼每走一步时，方向都是随机的。经过时间t之后，计算出这个酒鬼与原点的距离。（例如：这个酒鬼走了2000步，每步0.5米， 向前走一步记作1，向后走一步记作-1）

In [15]:
import numpy as np

In [16]:
steps = 2000
# np.random.randint?
# 通过 randint 函数模拟酒鬼随机走2000步
draws = np.random.randint(0, 2, size=steps)
draws

array([0, 0, 0, ..., 1, 1, 0])

In [17]:
# 当元素为1时， direction_steps为1
# 当元素为-1时， direction_steps为-1
direction_steps = np.where(draws > 0, 1, -1)
direction_steps

array([-1, -1, -1, ...,  1,  1, -1])

In [19]:
# 计算所有元素的累计和，即所有步数的累计和。
distance = direction_steps.cumsum()
distance

array([ -1,  -2,  -3, ..., -50, -49, -50], dtype=int32)

#### 当酒鬼距离原点大于或等于15米时，计算出这个酒鬼走了多少步？


In [20]:
# 计算当酒鬼距离原点大于或等于15米时走的累计步数
steps = 15/0.5
steps

30.0

In [24]:
(np.abs(distance) >= steps).argmax()

295